version: '3.6'
services:
  dev:
    build:
        context: .
        target: dev
    ports:
        - "8888:8080"
        - "3000:3000"
    env_file:
        - .env.ci
    depends_on:
        - db
    command: gunicorn --chdir /opt/app/src --bind 0.0.0.0:8080 --workers 1 time_manager.wsgi:application --reload --timeout 9999
  db:
    build:
        context: .
        target: db
    ports:
        - "5432:5432"
    environment:
        - POSTGRES_PASSWORD=password
        - POSTGRES_USER=admin
        - POSTGRES_DB=time_manager
    volumes:
        - postgres:/var/lib/postgresql/data

volumes:
    postgres:
        name: db_volume
