version: '3.6'
services:
  service:
    build:
      context: .
      target: service
      args:
        - POSTGRES_DB=time_manager
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: uvicorn time_manager.main:app --host 0.0.0.0 --port 3000
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=time_manager
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: db_volume
