version: '3.6'
services:
  service:
    build:
        context: .
        target: service
    ports:
        - "3000:3000"
    command: python3 -m uvicorn time_manager.main:app --host 0.0.0.0 --port 3000
