# Generated by Django 3.0.6 on 2020-05-20 14:54

from django.db import migrations, models
import django.db.models.deletion

from ..utils import constants

def populate_request_types(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    RequestType = apps.get_model('core', 'RequestType')
    for i in constants.Request:
        RequestType(id=i.value, rtype=i.name).save()


def depopulate_request_types(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtype', models.TextField(editable=False, unique=True)),
            ],
        ),
        migrations.RunPython(populate_request_types, reverse_code=depopulate_request_types),

        migrations.AlterField(
            model_name='date',
            name='ts',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='rtype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.RequestType'),
        ),
    ]
