# Generated by Django 3.0.7 on 2020-06-17 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200611_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=None, null=True)),
                ('end', models.DateTimeField(default=None, null=True)),
                ('rtype', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.RequestType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='request',
            name='rtype',
        ),
        migrations.RemoveField(
            model_name='request',
            name='ts',
        ),
        migrations.RemoveField(
            model_name='request',
            name='user',
        ),
        migrations.DeleteModel(
            name='Date',
        ),
        migrations.AlterField(
            model_name='comment',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TimeRequest'),
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
